### ISSUE TITLE
npm i error

### ISSUE THREAD

**Issue by GrizzlyRP** [SpaceTheDev/sDiscord#2]
installing the requirements through npm does not work with this.

Yes I have node.js installed, latest recommended version.

![2021-03-28 04_34_26-51 81 49 18 - Remote Desktop Connection](https://user-images.githubusercontent.com/49042906/112746746-f12f6b00-8f7e-11eb-8de8-5a56f166884e.png)

**Comment by Dalrae1** [comment]
Dont use powershell
